In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from scipy.stats import norm
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

In [10]:
# Function 5
print('Function 5')
func5_inputs = np.load('./initial_data/function_5/initial_inputs.npy')
print(func5_inputs)

func5_outputs = np.load('./initial_data/function_5/initial_outputs.npy')
print(func5_outputs)
print('/n')

Function 5
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]]
[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.

In [11]:
# Week 1 Input and Output Data
week_1_inputs = [ np.array([0.155793, 0.528435]), np.array([0.224164, 0.812385]), np.array([0.830919, 0.158523, 0.528406]), np.array([0.912533, 0.052672, 0.771239, 0.219812]), np.array([0.234189, 0.83648 , 0.884484, 0.873516]), np.array([0.490808, 0.618683, 0.277824, 0.900494, 0.106596]), np.array([0.067896, 0.486672, 0.255422, 0.215118, 0.427428, 0.72097 ]), np.array([0.061447, 0.062956, 0.029929, 0.036786, 0.407935, 0.795055, 0.496307,0.888085]) ]
week_1_outputs = [np.float64(1.5311489892413605e-58), np.float64(0.04614596805685454), np.float64(-0.04591165123945737), np.float64(-24.387232512869755), np.float64(1049.4420694211206), np.float64(-0.849252655626155), np.float64(1.3793294734939503), np.float64(9.598780741169)]

week_2_inputs = [np.array([0.946399, 0.18731 ]), np.array([0.712637, 0.921564]), np.array([0.765104, 0.052672, 0.438597]), np.array([0.380965, 0.771701, 0.089479, 0.536968]), np.array([0.219189, 0.85148 , 0.874484, 0.883516]), np.array([0.114755, 0.697421, 0.354179, 0.887624, 0.589139]), np.array([0.070896, 0.484672, 0.259422, 0.216118, 0.427428, 0.72297 ]), np.array([0.062447, 0.061956, 0.030929, 0.035786, 0.408935, 0.794055, 0.497307, 0.887085])]
week_2_outputs = [np.float64(2.338449488843798e-206), np.float64(0.5728372778652475), np.float64(-0.10235480701941752), np.float64(-13.368584815829887), np.float64(1109.9883069580462), np.float64(-1.492909868264592), np.float64(1.3944037721068683), np.float64(9.598978827169)]

week_3_inputs = [np.array([0.583738, 0.706798]), np.array([0.699637, 0.928564]), np.array([0.123457, 0.876543, 0.5     ]), np.array([0.230785, 0.914568, 0.102938, 0.657322]), np.array([0.214189, 0.85648 , 0.869484, 0.888516]), np.array([0.051235, 0.987654, 0.43211 , 0.123457, 0.765432]), np.array([0.071896, 0.483672, 0.261422, 0.217118, 0.426428, 0.72497 ]), np.array([0.063447, 0.060956, 0.031929, 0.034786, 0.409935, 0.793055, 0.498307, 0.886085])]
week_3_outputs = [np.float64(9.817718646044271e-07), np.float64(0.49978778689465564), np.float64(-0.04054152149606349), np.float64(-21.112987453792396), np.float64(1132.5255136709882), np.float64(-2.4679805862566795), np.float64(1.4059619293543582), np.float64(9.599155713169)]

week_4_inputs = [np.array([0.867072, 0.913241]), np.array([0.83604 , 0.696071]), np.array([0.447658, 0.395195, 0.505344]), np.array([0.422706, 0.385497, 0.37529 , 0.410833]), np.array([0.157706, 0.912326, 0.830158, 0.925715]), np.array([0.275401, 0.      , 0.568079, 1.      , 0.121326]), np.array([0.124679, 0.389027, 0.389012, 0.23686 , 0.379036, 0.802247]), np.array([0.077447, 0.21029 , 0.114032, 0.159535, 0.695924, 0.531316,0.178973, 0.57168 ])]
week_4_outputs = [np.float64(-1.0508862613282513e-96), np.float64(0.20657541488475104), np.float64(-0.03229682155733878), np.float64(0.4964978124935766), np.float64(1445.380906735266), np.float64(-0.8152779914672599), np.float64(2.0217812896063525), np.float64(9.987130922543)]

week_5_inputs = [np.array([0.065052, 0.948886]), np.array([0.388677, 0.271349]), np.array([1.      , 0.136717, 0.850593]), np.array([0.908266, 0.239562, 0.144895, 0.489453]), np.array([0.115614, 0.955641, 0.820859, 0.938174]), np.array([0.568442, 0.      , 1.      , 1.      , 1.      ]), np.array([0.134015, 0.028783, 0.755137, 0.62031 , 0.70408 , 0.212964]), np.array([0.127008, 0.292876, 0.06967 , 0.277582, 0.553407, 0.547258,0.220835, 0.443146])]
week_5_outputs = [np.float64(2.0262778967114778e-283), np.float64(0.016418658339648333), np.float64(-0.054388754089278846), np.float64(-17.161465002411145), np.float64(1779.8600577462366), np.float64(-1.9906490554141107), np.float64(0.052467603616080494), np.float64(9.9149654065019)]

week_6_inputs = [np.array([0.17701 , 0.088703]), np.array([0.593592, 0.679102]), np.array([0.7536, 1.    , 1.    ]), np.array([0.370348, 0.379959, 0.430216, 0.444351]), np.array([0.169493, 0.556801, 0.936155, 0.69603 ]), np.array([0.366464, 0.316099, 1.      , 1.      , 0.      ]), np.array([0.123574, 0.270452, 0.482301, 0.208163, 0.330398, 0.872733]), np.array([0.3191  , 0.828915, 0.037008, 0.59627 , 0.230009, 0.120567,0.076953, 0.696289])]
week_6_outputs = [np.float64(-2.3725238219366144e-119), np.float64(0.06836721478932847), np.float64(-0.48310415434111403), np.float64(0.18076540708623456), np.float64(282.83820524691396), np.float64(-0.8214281898088153), np.float64(2.075605759888563), np.float64(8.8803427965834)]

week_7_inputs = [np.array([0.065052, 0.948886]), np.array([0.140924, 0.802197]), np.array([1., 1., 0.]), np.array([0.32078 , 0.186519, 0.040775, 0.590893]), np.array([0.548734, 0.691895, 0.651961, 0.224269]), np.array([0.368433, 0.      , 1.      , 1.      , 0.428022]), np.array([0.139689, 0.317433, 0.463608, 0.250431, 0.325485, 0.810756]), np.array([0.      , 0.202823, 0.231703, 0.      , 1.      , 1.      ,
       0.288474, 1.      ])]
week_7_outputs = [np.float64(2.0262778967114778e-283), np.float64(-0.10826299524356352), np.float64(-0.16354530625442043), np.float64(-11.58523458824008), np.float64(1.9931553503870212), np.float64(-1.2796687884296385), np.float64(2.462201676843452), np.float64(9.622023932692)]

week_8_inputs = [np.array([0.000788, 0.033717]), np.array([0.914607, 0.789979]), np.array([0.317253, 0.002183, 0.963506]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.078217, 0.973099, 0.868006, 0.933352]), np.array([0.426158, 0.348959, 0.616644, 0.692851, 0.024814]), np.array([0.269889, 0.346609, 0.467584, 0.256632, 0.302654, 0.800092]), np.array([0.066269, 0.029193, 0.143059, 0.209133, 0.840619, 0.604919,
       0.230297, 0.701468])]
week_8_outputs = [np.float64(1.5608341712501477e-228), np.float64(0.0347797753016137), np.float64(-0.3756702789549372), np.float64(-33.661790988299735), np.float64(2151.3700669834334), np.float64(-0.23000336822278494), np.float64(2.4516632535923746), np.float64(9.9644234438351)]

week_9_inputs = [np.array([0.000924, 0.003116]), np.array([0.914607, 0.789979]), np.array([0.047574, 0.998325, 0.999125]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.080698, 0.971918, 0.842327, 0.954471]), np.array([0.942348, 0.037756, 0.105925, 0.010348, 0.997595]), np.array([0.090198, 0.680559, 0.851748, 0.080076, 0.298474, 0.701193]), np.array([0.95983 , 0.002073, 0.011779, 0.227207, 0.571611, 0.031204,
       0.24468 , 0.055697])]
week_9_outputs = [np.float64(7.25285761175276e-246), np.float64(0.05670257386671321), np.float64(-0.48158498276260003), np.float64(-33.661790988299735), np.float64(2156.522419821577), np.float64(-3.026993482898997), np.float64(0.6117443854593981), np.float64(8.1721431718416)]

week_10_inputs = [np.array([0.999878, 0.001995]), np.array([0.41611 , 0.666998]), np.array([0.001378, 0.999625, 0.642937]), np.array([0.027746, 0.654937, 0.999652, 0.024674]), np.array([0.109191, 0.976767, 0.866838, 0.873854]), np.array([0.944032, 0.013284, 0.976966, 0.023315, 0.997903]), np.array([0.167912, 0.257921, 0.480203, 0.472529, 0.254657, 0.778833]), np.array([0.116951, 0.002708, 0.212486, 0.121597, 0.986678, 0.488014,
       0.152731, 0.379341])]
week_10_outputs = [np.float64(0.0), np.float64(0.1625184332362701), np.float64(-0.13457392031599885), np.float64(-30.133085064011215), np.float64(1769.6901405375768), np.float64(-2.7724961974553874), np.float64(1.9208154093840464), np.float64(9.9296060847489)]

week_11_inputs = [np.array([0.37454 , 0.950714]), np.array([0.41611 , 0.666998]), np.array([0.997078, 0.475121, 0.651523]), np.array([0.00109 , 0.902069, 0.972212, 0.16754 ]), np.array([0.019324, 0.941663, 0.833048, 0.950636]), np.array([0.973398, 0.011482, 0.130865, 0.931063, 0.997256]), np.array([0.215391, 0.288991, 0.602008, 0.322698, 0.265768, 0.811541]), np.array([0.16109 , 0.049964, 0.210829, 0.130137, 0.965223, 0.408414,
       0.113403, 0.289162])]
week_11_outputs = [np.float64(-1.560646704467778e-117), np.float64(-0.1334547156009971), np.float64(-0.10208280924057045), np.float64(-31.74483921038956), np.float64(1827.9676185989063), np.float64(-2.432448557520746), np.float64(2.4819294367786457), np.float64(9.9158368797091)]

In [12]:
# Function 5
print('Function 5')
# Load inputs from previous run
# Loads initial data
week_0_func5_inputs = np.load('./initial_data/function_5/initial_inputs.npy')
week_0_func5_outputs = np.load('./initial_data/function_5/initial_outputs.npy')

print(f'Shape of initial input data: {week_0_func5_inputs.shape}')
print(f'Shape of initial output data: {week_0_func5_outputs.shape}')

print(f'Week 1 inputs: {week_1_inputs[4]}')
print(f'Week 2 inputs: {week_2_inputs[4]}')
print(f'Week 3 inputs: {week_3_inputs[4]}')
print(f'Week 4 inputs: {week_4_inputs[4]}')
print(f'Week 5 inputs: {week_5_inputs[4]}')
print(f'Week 6 inputs: {week_6_inputs[4]}')
print(f'Week 7 inputs: {week_7_inputs[4]}')
print(f'Week 8 inputs: {week_8_inputs[4]}')
print(f'Week 9 inputs: {week_9_inputs[4]}')
print(f'Week 10 inputs: {week_10_inputs[4]}')
print(f'Week 11 inputs: {week_11_inputs[4]}')

combined_func5_inputs = np.vstack([
    week_0_func5_inputs,
    week_1_inputs[4],
    week_2_inputs[4],
    week_3_inputs[4],
    week_4_inputs[4],
    week_5_inputs[4],
    week_6_inputs[4],
    week_7_inputs[4],
    week_8_inputs[4],
    week_9_inputs[4],
    week_10_inputs[4],
    week_11_inputs[4]
])
print(f'Number of input data points: {len(combined_func5_inputs)}')
print('Combined input data')
print(combined_func5_inputs)

# Load outputs from previous run
week_func5_output = week_1_outputs[4]
combined_func5_outputs = np.concatenate([
    week_0_func5_outputs,
    [week_1_outputs[4]],
    [week_2_outputs[4]],
    [week_3_outputs[4]],
    [week_4_outputs[4]],
    [week_5_outputs[4]],
    [week_6_outputs[4]],
    [week_7_outputs[4]],
    [week_8_outputs[4]],
    [week_9_outputs[4]],
    [week_10_outputs[4]],
    [week_11_outputs[4]]
])
print(f'Number of output data points: {len(combined_func5_outputs)}')
print('Combined output data')
print(combined_func5_outputs)

Function 5
Shape of initial input data: (20, 4)
Shape of initial output data: (20,)
Week 1 inputs: [0.234189 0.83648  0.884484 0.873516]
Week 2 inputs: [0.219189 0.85148  0.874484 0.883516]
Week 3 inputs: [0.214189 0.85648  0.869484 0.888516]
Week 4 inputs: [0.157706 0.912326 0.830158 0.925715]
Week 5 inputs: [0.115614 0.955641 0.820859 0.938174]
Week 6 inputs: [0.169493 0.556801 0.936155 0.69603 ]
Week 7 inputs: [0.548734 0.691895 0.651961 0.224269]
Week 8 inputs: [0.078217 0.973099 0.868006 0.933352]
Week 9 inputs: [0.080698 0.971918 0.842327 0.954471]
Week 10 inputs: [0.109191 0.976767 0.866838 0.873854]
Week 11 inputs: [0.019324 0.941663 0.833048 0.950636]
Number of input data points: 31
Combined input data
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.5675766

In [13]:
### ====== OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 5 ======
# Import the OptunaBayesianOptimizer class
import sys
sys.path.insert(0, './bayesian_optimization_challenge-md')
from bo_optuna import OptunaBayesianOptimizer

# Create optimizer instance with initial Function 5 data
print("=" * 60)
print("OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 5")
print("=" * 60)

X_func5_initial = week_0_func5_inputs
y_func5_initial = week_0_func5_outputs
bounds_func5 = [(0, 1)] * X_func5_initial.shape[1]

optimizer_func5 = OptunaBayesianOptimizer(
    X_initial=X_func5_initial,
    y_initial=y_func5_initial,
    bounds=bounds_func5,
    optimize_hp=True,  # Enable hyperparameter tuning
    random_state=42,
    acquisition="ucb",
    hp = {
        'constant': 1.0,
        'length_scale': 0.5,
        'kappa': 100.0,
        'xi': 0.01,
        'alpha': 1e-6
    }
)

print(f"\nInitial training data shape: X={optimizer_func5.X_train.shape}, y={optimizer_func5.y_train.shape}")
print(f"Initial best observation: {optimizer_func5.get_best_observation()[1]:.6e}")


OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 5

Initial training data shape: X=(20, 4), y=(20,)
Initial best observation: 1.088860e+03


In [14]:
# Run Optuna-based BO for 8 weeks (8 iterations)
print("\nRunning Optuna-based BO for 8 iterations...")
print("-" * 60)

# Get all weekly data
weekly_data = [
    (week_1_inputs[4], week_1_outputs[4]),
    (week_2_inputs[4], week_2_outputs[4]),
    (week_3_inputs[4], week_3_outputs[4]),
    (week_4_inputs[4], week_4_outputs[4]),
    (week_5_inputs[4], week_5_outputs[4]),
    (week_6_inputs[4], week_6_outputs[4]),
    (week_7_inputs[4], week_7_outputs[4]),
    (week_8_inputs[4], week_8_outputs[4]),
    (week_9_inputs[4], week_9_outputs[4]),
    (week_10_inputs[4], week_10_outputs[4]),
    (week_11_inputs[4], week_11_outputs[4])
]

optuna_proposals_func5 = []
manual_best_func5 = week_0_func5_outputs.max()
optuna_best_func5 = y_func5_initial.max()

for week, (x_actual, y_actual) in enumerate(weekly_data, start=1):
    print(f"\nWeek {week}:")
    print(f"  Actual observation: y = {y_actual:.6e}")
    
    # Get Optuna proposal
    proposals = optimizer_func5.optimize(
        n_iterations=1,
        optimize_hp_every=1 if week % 2 == 0 else 0,  # Tune HP every other week
        optimize_hp_n_trials=30,
        acq_n_trials=100,
        verbose=True
    )
    
    x_proposed = proposals[0]
    optuna_proposals_func5.append(x_proposed)
    
    # Update optimizer with actual observation
    optimizer_func5.update(x_actual, y_actual)
    
    # Track best values
    manual_best_func5 = max(manual_best_func5, y_actual)
    optuna_best_func5 = max(optuna_best_func5, y_actual)
    
    print(f"  Best so far (Optuna): {optuna_best_func5:.6e}")

print("\n" + "=" * 60)
print("OPTUNA-BASED BO COMPLETED FOR FUNCTION 5")
print("=" * 60)



Running Optuna-based BO for 8 iterations...
------------------------------------------------------------

Week 1:
  Actual observation: y = 1.049442e+03


[I 2026-04-28 02:57:43,191] A new study created in memory with name: no-name-9fb0829d-5dfb-4713-b7c6-d017cb19bba5
[I 2026-04-28 02:57:43,236] Trial 0 finished with value: 636.2321576314451 and parameters: {'x0': 0.3745401188473625, 'x1': 0.9507143064099162, 'x2': 0.7319939418114051, 'x3': 0.5986584841970366}. Best is trial 0 with value: 636.2321576314451.
[I 2026-04-28 02:57:43,237] Trial 1 finished with value: 480.03560197432415 and parameters: {'x0': 0.15601864044243652, 'x1': 0.15599452033620265, 'x2': 0.05808361216819946, 'x3': 0.8661761457749352}. Best is trial 0 with value: 636.2321576314451.
[I 2026-04-28 02:57:43,239] Trial 2 finished with value: 495.9993233685569 and parameters: {'x0': 0.6011150117432088, 'x1': 0.7080725777960455, 'x2': 0.020584494295802447, 'x3': 0.9699098521619943}. Best is trial 0 with value: 636.2321576314451.
[I 2026-04-28 02:57:43,241] Trial 3 finished with value: 475.2171244702262 and parameters: {'x0': 0.8324426408004217, 'x1': 0.21233911067827616, 'x2

[Iteration 0] Proposed: [0.19541184 0.80909552 0.90468384 0.93146611], UCB: 1185.043476
  Best so far (Optuna): 1.088860e+03

Week 2:
  Actual observation: y = 1.109988e+03


[I 2026-04-28 02:57:44,439] Trial 22 finished with value: 1189.5081409571353 and parameters: {'x0': 0.23716233471398815, 'x1': 0.8253314741429714, 'x2': 0.7996608319013745, 'x3': 0.8769751623406266}. Best is trial 22 with value: 1189.5081409571353.
[I 2026-04-28 02:57:44,450] Trial 23 finished with value: 479.3785459894104 and parameters: {'x0': 0.1394999464280174, 'x1': 0.6196953501962026, 'x2': 0.6024857090862797, 'x3': 0.020913566483403923}. Best is trial 22 with value: 1189.5081409571353.
[I 2026-04-28 02:57:44,460] Trial 24 finished with value: 939.8373991210801 and parameters: {'x0': 0.3656434951848247, 'x1': 0.8641270169593515, 'x2': 0.8647646799564714, 'x3': 0.9123844351317147}. Best is trial 22 with value: 1189.5081409571353.
[I 2026-04-28 02:57:44,472] Trial 25 finished with value: 482.3607835952282 and parameters: {'x0': 0.5390832704918319, 'x1': 0.7330249019989907, 'x2': 0.7758248860496252, 'x3': 0.6420863074101599}. Best is trial 22 with value: 1189.5081409571353.
[I 2026-

[Iteration 0] Proposed: [0.18487093 0.8873717  0.8720994  0.8554198 ], UCB: 1224.234000
  Best so far (Optuna): 1.109988e+03

Week 3:
  Actual observation: y = 1.132526e+03


[I 2026-04-28 02:57:45,592] Trial 23 finished with value: 475.15520700211255 and parameters: {'x0': 0.5192650009106206, 'x1': 0.6196953501962026, 'x2': 0.7724697396519256, 'x3': 0.020913566483403923}. Best is trial 14 with value: 1140.074812053511.
[I 2026-04-28 02:57:45,603] Trial 24 finished with value: 544.9687863954787 and parameters: {'x0': 0.11123017956285984, 'x1': 0.8641270169593515, 'x2': 0.6293286660298152, 'x3': 0.6637684454608606}. Best is trial 14 with value: 1140.074812053511.
[I 2026-04-28 02:57:45,614] Trial 25 finished with value: 569.5827565723646 and parameters: {'x0': 0.23624144133281572, 'x1': 0.7330249019989907, 'x2': 0.5038371831453836, 'x3': 0.7895923125074197}. Best is trial 14 with value: 1140.074812053511.
[I 2026-04-28 02:57:45,625] Trial 26 finished with value: 485.25774979806516 and parameters: {'x0': 0.18472340464412956, 'x1': 0.40742273866493767, 'x2': 0.8773649013684935, 'x3': 0.8702259882594467}. Best is trial 14 with value: 1140.074812053511.
[I 2026-

[Iteration 0] Proposed: [0.19209801 0.82508768 0.84633325 0.9410277 ], UCB: 1208.452380
  Best so far (Optuna): 1.132526e+03

Week 4:
  Actual observation: y = 1.445381e+03


[I 2026-04-28 02:57:46,578] Trial 23 finished with value: 474.34837680483656 and parameters: {'x0': 0.3062442572998052, 'x1': 0.1463656951698548, 'x2': 0.5798442552347269, 'x3': 0.4853414839159519}. Best is trial 5 with value: 478.3303053477482.
[I 2026-04-28 02:57:46,588] Trial 24 finished with value: 474.3416781276753 and parameters: {'x0': 0.0023017083042986552, 'x1': 0.002794897010009234, 'x2': 0.6499714086831934, 'x3': 0.314548532160141}. Best is trial 5 with value: 478.3303053477482.
[I 2026-04-28 02:57:46,598] Trial 25 finished with value: 474.34173751140503 and parameters: {'x0': 0.505253197799544, 'x1': 0.24871608465213507, 'x2': 0.4766743630226802, 'x3': 0.5386175517915082}. Best is trial 5 with value: 478.3303053477482.
[I 2026-04-28 02:57:46,607] Trial 26 finished with value: 474.34181517656845 and parameters: {'x0': 0.6387363441263871, 'x1': 0.39492238669930446, 'x2': 0.30366200445293495, 'x3': 0.3903586307534025}. Best is trial 5 with value: 478.3303053477482.
[I 2026-04-

[Iteration 0] Proposed: [0.13595137 0.04077047 0.55266993 0.43901216], UCB: 478.699014
  Best so far (Optuna): 1.445381e+03

Week 5:
  Actual observation: y = 1.779860e+03


[I 2026-04-28 02:57:47,562] Trial 23 finished with value: 474.3578483232837 and parameters: {'x0': 0.6748483284313452, 'x1': 0.8557335973538435, 'x2': 0.7455203911755207, 'x3': 0.6140281041712762}. Best is trial 8 with value: 740.7311292559909.
[I 2026-04-28 02:57:47,572] Trial 24 finished with value: 481.4252114989859 and parameters: {'x0': 0.2863426508277455, 'x1': 0.6080099974578267, 'x2': 0.6293286660298152, 'x3': 0.7694758726233963}. Best is trial 8 with value: 740.7311292559909.
[I 2026-04-28 02:57:47,581] Trial 25 finished with value: 474.35757262557837 and parameters: {'x0': 0.11224181847081638, 'x1': 0.3415500949354924, 'x2': 0.9094981363573335, 'x3': 0.9022927089198993}. Best is trial 8 with value: 740.7311292559909.
[I 2026-04-28 02:57:47,591] Trial 26 finished with value: 474.2484792486026 and parameters: {'x0': 0.5294968141748467, 'x1': 0.5400954272881503, 'x2': 0.5268254872812902, 'x3': 0.7091065638707792}. Best is trial 8 with value: 740.7311292559909.
[I 2026-04-28 02:5

[Iteration 0] Proposed: [0.12972831 0.89572711 0.83056595 0.88983158], UCB: 1536.629940
  Best so far (Optuna): 1.779860e+03

Week 6:
  Actual observation: y = 2.828382e+02


[I 2026-04-28 02:57:48,533] Trial 23 finished with value: 474.34166800151013 and parameters: {'x0': 0.6748483284313452, 'x1': 0.8557335973538435, 'x2': 0.7455203911755207, 'x3': 0.6140281041712762}. Best is trial 8 with value: 577.2189507475711.
[I 2026-04-28 02:57:48,543] Trial 24 finished with value: 474.5821192158457 and parameters: {'x0': 0.2863426508277455, 'x1': 0.6080099974578267, 'x2': 0.6293286660298152, 'x3': 0.7694758726233963}. Best is trial 8 with value: 577.2189507475711.
[I 2026-04-28 02:57:48,554] Trial 25 finished with value: 474.34165242061323 and parameters: {'x0': 0.11224181847081638, 'x1': 0.3415500949354924, 'x2': 0.9094981363573335, 'x3': 0.9022927089198993}. Best is trial 8 with value: 577.2189507475711.
[I 2026-04-28 02:57:48,565] Trial 26 finished with value: 474.5607870451452 and parameters: {'x0': 0.5294968141748467, 'x1': 0.5400954272881503, 'x2': 0.5268254872812902, 'x3': 0.7091065638707792}. Best is trial 8 with value: 577.2189507475711.
[I 2026-04-28 02:

[Iteration 0] Proposed: [0.12274854 0.96064835 0.84448788 0.957546  ], UCB: 1836.665656
  Best so far (Optuna): 1.779860e+03

Week 7:
  Actual observation: y = 1.993155e+00


[I 2026-04-28 02:57:49,545] Trial 25 finished with value: 640.0579522478229 and parameters: {'x0': 0.367257326720235, 'x1': 0.8014344700557612, 'x2': 0.8970752229277679, 'x3': 0.7695904215007623}. Best is trial 17 with value: 1174.352730465473.
[I 2026-04-28 02:57:49,559] Trial 26 finished with value: 478.12911197878907 and parameters: {'x0': 0.10194389266183096, 'x1': 0.8768572993966747, 'x2': 0.7712198276505244, 'x3': 0.6264789135516162}. Best is trial 17 with value: 1174.352730465473.
[I 2026-04-28 02:57:49,569] Trial 27 finished with value: 474.607309862572 and parameters: {'x0': 0.2081235584111811, 'x1': 0.6112825305227232, 'x2': 0.573689467505592, 'x3': 0.9985454121176579}. Best is trial 17 with value: 1174.352730465473.
[I 2026-04-28 02:57:49,579] Trial 28 finished with value: 714.5242703495097 and parameters: {'x0': 0.3444030438011549, 'x1': 0.795867761893573, 'x2': 0.8894178389489176, 'x3': 0.9026571487153402}. Best is trial 17 with value: 1174.352730465473.
[I 2026-04-28 02:5

[Iteration 0] Proposed: [0.08069772 0.97191835 0.84232679 0.9544711 ], UCB: 1820.312229
  Best so far (Optuna): 1.779860e+03

Week 8:
  Actual observation: y = 2.151370e+03


[I 2026-04-28 02:57:50,511] Trial 21 finished with value: 829.9558285357175 and parameters: {'x0': 0.12422264173647583, 'x1': 0.9078043738860397, 'x2': 0.8950069249108467, 'x3': 0.7991693370845518}. Best is trial 17 with value: 1174.3437509557111.
[I 2026-04-28 02:57:50,519] Trial 22 finished with value: 1014.9791946576933 and parameters: {'x0': 0.12267641481069463, 'x1': 0.8145901286801429, 'x2': 0.8561330797535327, 'x3': 0.9338659659085237}. Best is trial 17 with value: 1174.3437509557111.
[I 2026-04-28 02:57:50,531] Trial 23 finished with value: 556.1398497161763 and parameters: {'x0': 0.274084276854932, 'x1': 0.7481399359566338, 'x2': 0.7490504115476642, 'x3': 0.9162914504115097}. Best is trial 17 with value: 1174.3437509557111.
[I 2026-04-28 02:57:50,540] Trial 24 finished with value: 475.86860773629746 and parameters: {'x0': 0.22671594911668524, 'x1': 0.6259979248264684, 'x2': 0.6605992458284577, 'x3': 0.9468049264135635}. Best is trial 17 with value: 1174.3437509557111.
[I 2026-

[Iteration 0] Proposed: [0.08069772 0.97191835 0.84232679 0.9544711 ], UCB: 1820.292421
  Best so far (Optuna): 2.151370e+03

Week 9:
  Actual observation: y = 2.156522e+03


[I 2026-04-28 02:57:51,519] Trial 24 finished with value: 701.7136590784437 and parameters: {'x0': 0.10523051662937362, 'x1': 0.9937481669780763, 'x2': 0.6293286660298152, 'x3': 0.9296560899084381}. Best is trial 14 with value: 1481.9441162534483.
[I 2026-04-28 02:57:51,529] Trial 25 finished with value: 842.2435129385249 and parameters: {'x0': 0.13677382042803835, 'x1': 0.7269647517880445, 'x2': 0.897003176314259, 'x3': 0.8046078042180431}. Best is trial 14 with value: 1481.9441162534483.
[I 2026-04-28 02:57:51,539] Trial 26 finished with value: 865.2403445640687 and parameters: {'x0': 0.33328463884573495, 'x1': 0.9315886570046443, 'x2': 0.9167836141358221, 'x3': 0.8481882943405639}. Best is trial 14 with value: 1481.9441162534483.
[I 2026-04-28 02:57:51,549] Trial 27 finished with value: 483.1616053991609 and parameters: {'x0': 0.7394529050577365, 'x1': 0.3203397352579168, 'x2': 0.7389905924292726, 'x3': 0.9980738746350019}. Best is trial 14 with value: 1481.9441162534483.
[I 2026-04

[Iteration 0] Proposed: [0.10919128 0.97676722 0.86683817 0.87385432], UCB: 2036.807833
  Best so far (Optuna): 2.156522e+03

Week 10:
  Actual observation: y = 1.769690e+03


[I 2026-04-28 02:57:52,512] Trial 23 finished with value: 651.8888099955425 and parameters: {'x0': 0.274084276854932, 'x1': 0.7481399359566338, 'x2': 0.7490504115476642, 'x3': 0.9162914504115097}. Best is trial 22 with value: 1313.2334845544153.
[I 2026-04-28 02:57:52,521] Trial 24 finished with value: 490.13855854387606 and parameters: {'x0': 0.22671594911668524, 'x1': 0.6259979248264684, 'x2': 0.6605992458284577, 'x3': 0.9468049264135635}. Best is trial 22 with value: 1313.2334845544153.
[I 2026-04-28 02:57:52,532] Trial 25 finished with value: 773.2725287253854 and parameters: {'x0': 0.367257326720235, 'x1': 0.8014344700557612, 'x2': 0.8970752229277679, 'x3': 0.7695904215007623}. Best is trial 22 with value: 1313.2334845544153.
[I 2026-04-28 02:57:52,542] Trial 26 finished with value: 501.6808989463648 and parameters: {'x0': 0.10194389266183096, 'x1': 0.8768572993966747, 'x2': 0.7712198276505244, 'x3': 0.6264789135516162}. Best is trial 22 with value: 1313.2334845544153.
[I 2026-04-

[Iteration 0] Proposed: [0.01932424 0.94166253 0.83304784 0.95063612], UCB: 2086.875374
  Best so far (Optuna): 2.156522e+03

Week 11:
  Actual observation: y = 1.827968e+03


[I 2026-04-28 02:57:53,613] Trial 22 finished with value: 1146.3437270426534 and parameters: {'x0': 0.24391805846580486, 'x1': 0.8864167119179456, 'x2': 0.8560638476130187, 'x3': 0.8126326719151608}. Best is trial 14 with value: 1356.237733640964.
[I 2026-04-28 02:57:53,624] Trial 23 finished with value: 476.9140746927782 and parameters: {'x0': 0.3900335415910129, 'x1': 0.8156356366935824, 'x2': 0.7662726329599877, 'x3': 0.020913566483403923}. Best is trial 14 with value: 1356.237733640964.
[I 2026-04-28 02:57:53,635] Trial 24 finished with value: 567.6537530373546 and parameters: {'x0': 0.10523051662937362, 'x1': 0.9937481669780763, 'x2': 0.6293286660298152, 'x3': 0.9296560899084381}. Best is trial 14 with value: 1356.237733640964.
[I 2026-04-28 02:57:53,646] Trial 25 finished with value: 782.3316318552512 and parameters: {'x0': 0.13677382042803835, 'x1': 0.7269647517880445, 'x2': 0.897003176314259, 'x3': 0.8046078042180431}. Best is trial 14 with value: 1356.237733640964.
[I 2026-04-

[Iteration 0] Proposed: [0.06480697 0.97821456 0.85640431 0.97105933], UCB: 2248.262820
  Best so far (Optuna): 2.156522e+03

OPTUNA-BASED BO COMPLETED FOR FUNCTION 5
