In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from scipy.stats import norm
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

/Users/martindufour/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Function 4
print('Function 4')
func4_inputs = np.load('./initial_data/function_4/initial_inputs.npy')
print(func4_inputs)

func4_outputs = np.load('./initial_data/function_4/initial_outputs.npy')
print(func4_outputs)
print('/n')

Function 4
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [

In [3]:
# Week 1 Input and Output Data
week_1_inputs = [ np.array([0.155793, 0.528435]), np.array([0.224164, 0.812385]), np.array([0.830919, 0.158523, 0.528406]), np.array([0.912533, 0.052672, 0.771239, 0.219812]), np.array([0.234189, 0.83648 , 0.884484, 0.873516]), np.array([0.490808, 0.618683, 0.277824, 0.900494, 0.106596]), np.array([0.067896, 0.486672, 0.255422, 0.215118, 0.427428, 0.72097 ]), np.array([0.061447, 0.062956, 0.029929, 0.036786, 0.407935, 0.795055, 0.496307,0.888085]) ]
week_1_outputs = [np.float64(1.5311489892413605e-58), np.float64(0.04614596805685454), np.float64(-0.04591165123945737), np.float64(-24.387232512869755), np.float64(1049.4420694211206), np.float64(-0.849252655626155), np.float64(1.3793294734939503), np.float64(9.598780741169)]

week_2_inputs = [np.array([0.946399, 0.18731 ]), np.array([0.712637, 0.921564]), np.array([0.765104, 0.052672, 0.438597]), np.array([0.380965, 0.771701, 0.089479, 0.536968]), np.array([0.219189, 0.85148 , 0.874484, 0.883516]), np.array([0.114755, 0.697421, 0.354179, 0.887624, 0.589139]), np.array([0.070896, 0.484672, 0.259422, 0.216118, 0.427428, 0.72297 ]), np.array([0.062447, 0.061956, 0.030929, 0.035786, 0.408935, 0.794055, 0.497307, 0.887085])]
week_2_outputs = [np.float64(2.338449488843798e-206), np.float64(0.5728372778652475), np.float64(-0.10235480701941752), np.float64(-13.368584815829887), np.float64(1109.9883069580462), np.float64(-1.492909868264592), np.float64(1.3944037721068683), np.float64(9.598978827169)]

week_3_inputs = [np.array([0.583738, 0.706798]), np.array([0.699637, 0.928564]), np.array([0.123457, 0.876543, 0.5     ]), np.array([0.230785, 0.914568, 0.102938, 0.657322]), np.array([0.214189, 0.85648 , 0.869484, 0.888516]), np.array([0.051235, 0.987654, 0.43211 , 0.123457, 0.765432]), np.array([0.071896, 0.483672, 0.261422, 0.217118, 0.426428, 0.72497 ]), np.array([0.063447, 0.060956, 0.031929, 0.034786, 0.409935, 0.793055, 0.498307, 0.886085])]
week_3_outputs = [np.float64(9.817718646044271e-07), np.float64(0.49978778689465564), np.float64(-0.04054152149606349), np.float64(-21.112987453792396), np.float64(1132.5255136709882), np.float64(-2.4679805862566795), np.float64(1.4059619293543582), np.float64(9.599155713169)]

week_4_inputs = [np.array([0.867072, 0.913241]), np.array([0.83604 , 0.696071]), np.array([0.447658, 0.395195, 0.505344]), np.array([0.422706, 0.385497, 0.37529 , 0.410833]), np.array([0.157706, 0.912326, 0.830158, 0.925715]), np.array([0.275401, 0.      , 0.568079, 1.      , 0.121326]), np.array([0.124679, 0.389027, 0.389012, 0.23686 , 0.379036, 0.802247]), np.array([0.077447, 0.21029 , 0.114032, 0.159535, 0.695924, 0.531316,0.178973, 0.57168 ])]
week_4_outputs = [np.float64(-1.0508862613282513e-96), np.float64(0.20657541488475104), np.float64(-0.03229682155733878), np.float64(0.4964978124935766), np.float64(1445.380906735266), np.float64(-0.8152779914672599), np.float64(2.0217812896063525), np.float64(9.987130922543)]

week_5_inputs = [np.array([0.065052, 0.948886]), np.array([0.388677, 0.271349]), np.array([1.      , 0.136717, 0.850593]), np.array([0.908266, 0.239562, 0.144895, 0.489453]), np.array([0.115614, 0.955641, 0.820859, 0.938174]), np.array([0.568442, 0.      , 1.      , 1.      , 1.      ]), np.array([0.134015, 0.028783, 0.755137, 0.62031 , 0.70408 , 0.212964]), np.array([0.127008, 0.292876, 0.06967 , 0.277582, 0.553407, 0.547258,0.220835, 0.443146])]
week_5_outputs = [np.float64(2.0262778967114778e-283), np.float64(0.016418658339648333), np.float64(-0.054388754089278846), np.float64(-17.161465002411145), np.float64(1779.8600577462366), np.float64(-1.9906490554141107), np.float64(0.052467603616080494), np.float64(9.9149654065019)]

week_6_inputs = [np.array([0.17701 , 0.088703]), np.array([0.593592, 0.679102]), np.array([0.7536, 1.    , 1.    ]), np.array([0.370348, 0.379959, 0.430216, 0.444351]), np.array([0.169493, 0.556801, 0.936155, 0.69603 ]), np.array([0.366464, 0.316099, 1.      , 1.      , 0.      ]), np.array([0.123574, 0.270452, 0.482301, 0.208163, 0.330398, 0.872733]), np.array([0.3191  , 0.828915, 0.037008, 0.59627 , 0.230009, 0.120567,0.076953, 0.696289])]
week_6_outputs = [np.float64(-2.3725238219366144e-119), np.float64(0.06836721478932847), np.float64(-0.48310415434111403), np.float64(0.18076540708623456), np.float64(282.83820524691396), np.float64(-0.8214281898088153), np.float64(2.075605759888563), np.float64(8.8803427965834)]

week_7_inputs = [np.array([0.065052, 0.948886]), np.array([0.140924, 0.802197]), np.array([1., 1., 0.]), np.array([0.32078 , 0.186519, 0.040775, 0.590893]), np.array([0.548734, 0.691895, 0.651961, 0.224269]), np.array([0.368433, 0.      , 1.      , 1.      , 0.428022]), np.array([0.139689, 0.317433, 0.463608, 0.250431, 0.325485, 0.810756]), np.array([0.      , 0.202823, 0.231703, 0.      , 1.      , 1.      ,
       0.288474, 1.      ])]
week_7_outputs = [np.float64(2.0262778967114778e-283), np.float64(-0.10826299524356352), np.float64(-0.16354530625442043), np.float64(-11.58523458824008), np.float64(1.9931553503870212), np.float64(-1.2796687884296385), np.float64(2.462201676843452), np.float64(9.622023932692)]

week_8_inputs = [np.array([0.000788, 0.033717]), np.array([0.914607, 0.789979]), np.array([0.317253, 0.002183, 0.963506]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.078217, 0.973099, 0.868006, 0.933352]), np.array([0.426158, 0.348959, 0.616644, 0.692851, 0.024814]), np.array([0.269889, 0.346609, 0.467584, 0.256632, 0.302654, 0.800092]), np.array([0.066269, 0.029193, 0.143059, 0.209133, 0.840619, 0.604919,
       0.230297, 0.701468])]
week_8_outputs = [np.float64(1.5608341712501477e-228), np.float64(0.0347797753016137), np.float64(-0.3756702789549372), np.float64(-33.661790988299735), np.float64(2151.3700669834334), np.float64(-0.23000336822278494), np.float64(2.4516632535923746), np.float64(9.9644234438351)]

week_9_inputs = [np.array([0.000924, 0.003116]), np.array([0.914607, 0.789979]), np.array([0.047574, 0.998325, 0.999125]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.080698, 0.971918, 0.842327, 0.954471]), np.array([0.942348, 0.037756, 0.105925, 0.010348, 0.997595]), np.array([0.090198, 0.680559, 0.851748, 0.080076, 0.298474, 0.701193]), np.array([0.95983 , 0.002073, 0.011779, 0.227207, 0.571611, 0.031204,
       0.24468 , 0.055697])]
week_9_outputs = [np.float64(7.25285761175276e-246), np.float64(0.05670257386671321), np.float64(-0.48158498276260003), np.float64(-33.661790988299735), np.float64(2156.522419821577), np.float64(-3.026993482898997), np.float64(0.6117443854593981), np.float64(8.1721431718416)]

week_10_inputs = [np.array([0.999878, 0.001995]), np.array([0.41611 , 0.666998]), np.array([0.001378, 0.999625, 0.642937]), np.array([0.027746, 0.654937, 0.999652, 0.024674]), np.array([0.109191, 0.976767, 0.866838, 0.873854]), np.array([0.944032, 0.013284, 0.976966, 0.023315, 0.997903]), np.array([0.167912, 0.257921, 0.480203, 0.472529, 0.254657, 0.778833]), np.array([0.116951, 0.002708, 0.212486, 0.121597, 0.986678, 0.488014,
       0.152731, 0.379341])]
week_10_outputs = [np.float64(0.0), np.float64(0.1625184332362701), np.float64(-0.13457392031599885), np.float64(-30.133085064011215), np.float64(1769.6901405375768), np.float64(-2.7724961974553874), np.float64(1.9208154093840464), np.float64(9.9296060847489)]

week_11_inputs = [np.array([0.37454 , 0.950714]), np.array([0.41611 , 0.666998]), np.array([0.997078, 0.475121, 0.651523]), np.array([0.00109 , 0.902069, 0.972212, 0.16754 ]), np.array([0.019324, 0.941663, 0.833048, 0.950636]), np.array([0.973398, 0.011482, 0.130865, 0.931063, 0.997256]), np.array([0.215391, 0.288991, 0.602008, 0.322698, 0.265768, 0.811541]), np.array([0.16109 , 0.049964, 0.210829, 0.130137, 0.965223, 0.408414,
       0.113403, 0.289162])]
week_11_outputs = [np.float64(-1.560646704467778e-117), np.float64(-0.1334547156009971), np.float64(-0.10208280924057045), np.float64(-31.74483921038956), np.float64(1827.9676185989063), np.float64(-2.432448557520746), np.float64(2.4819294367786457), np.float64(9.9158368797091)]

week_12_inputs = [np.array([0.001   , 0.999576]), np.array([0.45253, 0.6577 ]), np.array([0.998539, 0.483668, 0.657653]), np.array([0.018818, 0.998904, 0.999658, 0.998016]), np.array([0.064807, 0.978215, 0.856404, 0.971059]), np.array([0.898391, 0.002198, 0.019804, 0.999554, 0.917075]), np.array([0.211376, 0.335246, 0.510659, 0.146838, 0.289515, 0.653795]), np.array([4.18000e-04, 1.05120e-02, 1.95045e-01, 2.11750e-01, 7.88533e-01,
       9.00374e-01, 2.41123e-01, 3.34541e-01])]
week_12_outputs = [np.float64(0.0), np.float64(0.3536071649472596), np.float64(-0.09423686717649356), np.float64(-47.62748092409266), np.float64(2449.5648412319215), np.float64(-2.500439911687528), np.float64(2.549261085159255), np.float64(9.7734101935864)]

In [4]:
# Function 4
print('Function 4')
# Load inputs from previous run
# Loads initial data
week_0_func4_inputs = np.load('./initial_data/function_4/initial_inputs.npy')
week_0_func4_outputs = np.load('./initial_data/function_4/initial_outputs.npy')

print(f'Shape of initial input data: {week_0_func4_inputs.shape}')
print(f'Shape of initial output data: {week_0_func4_outputs.shape}')

print(f'Week 1 inputs: {week_1_inputs[3]}')
print(f'Week 2 inputs: {week_2_inputs[3]}')
print(f'Week 3 inputs: {week_3_inputs[3]}')
print(f'Week 4 inputs: {week_4_inputs[3]}')
print(f'Week 5 inputs: {week_5_inputs[3]}')
print(f'Week 6 inputs: {week_6_inputs[3]}')
print(f'Week 7 inputs: {week_7_inputs[3]}')
print(f'Week 8 inputs: {week_8_inputs[3]}')
print(f'Week 9 inputs: {week_9_inputs[3]}')
print(f'Week 10 inputs: {week_10_inputs[3]}')
print(f'Week 11 inputs: {week_11_inputs[3]}')
print(f'Week 12 inputs: {week_12_inputs[3]}')

combined_func4_inputs = np.vstack([
    week_0_func4_inputs,
    week_1_inputs[3],
    week_2_inputs[3],
    week_3_inputs[3],
    week_4_inputs[3],
    week_5_inputs[3],
    week_6_inputs[3],
    week_7_inputs[3],
    week_8_inputs[3],
    week_9_inputs[3],
    week_10_inputs[3],
    week_11_inputs[3],
    week_12_inputs[3]
])
print(f'Number of input data points: {len(combined_func4_inputs)}')
print('Combined input data')
print(combined_func4_inputs)

# Load outputs from previous run
week_func4_output = week_1_outputs[3]
combined_func4_outputs = np.concatenate([
    week_0_func4_outputs,
    [week_1_outputs[3]],
    [week_2_outputs[3]],
    [week_3_outputs[3]],
    [week_4_outputs[3]],
    [week_5_outputs[3]],
    [week_6_outputs[3]],
    [week_7_outputs[3]],
    [week_8_outputs[3]],
    [week_9_outputs[3]],
    [week_10_outputs[3]],
    [week_11_outputs[3]],
    [week_12_outputs[3]]
])
print(f'Number of output data points: {len(combined_func4_outputs)}')
print('Combined output data')
print(combined_func4_outputs)

Function 4
Shape of initial input data: (30, 4)
Shape of initial output data: (30,)
Week 1 inputs: [0.912533 0.052672 0.771239 0.219812]
Week 2 inputs: [0.380965 0.771701 0.089479 0.536968]
Week 3 inputs: [0.230785 0.914568 0.102938 0.657322]
Week 4 inputs: [0.422706 0.385497 0.37529  0.410833]
Week 5 inputs: [0.908266 0.239562 0.144895 0.489453]
Week 6 inputs: [0.370348 0.379959 0.430216 0.444351]
Week 7 inputs: [0.32078  0.186519 0.040775 0.590893]
Week 8 inputs: [0.008334 0.234163 0.946857 0.993453]
Week 9 inputs: [0.008334 0.234163 0.946857 0.993453]
Week 10 inputs: [0.027746 0.654937 0.999652 0.024674]
Week 11 inputs: [0.00109  0.902069 0.972212 0.16754 ]
Week 12 inputs: [0.018818 0.998904 0.999658 0.998016]
Number of input data points: 42
Combined input data
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.

In [5]:
### ====== OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4 ======
# Import the OptunaBayesianOptimizer class
import sys
sys.path.insert(0, './bayesian_optimization_challenge-md')
from bo_optuna import OptunaBayesianOptimizer

# Create optimizer instance with initial Function 4 data
print("=" * 60)
print("OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4")
print("=" * 60)

X_func4_initial = week_0_func4_inputs
y_func4_initial = week_0_func4_outputs
bounds_func4 = [(0, 1)] * X_func4_initial.shape[1]

optimizer_func4 = OptunaBayesianOptimizer(
    X_initial=X_func4_initial,
    y_initial=y_func4_initial,
    bounds=bounds_func4,
    optimize_hp=True,  # Enable hyperparameter tuning
    random_state=42,
    acquisition="ucb"
)

print(f"\nInitial training data shape: X={optimizer_func4.X_train.shape}, y={optimizer_func4.y_train.shape}")
print(f"Initial best observation: {optimizer_func4.get_best_observation()[1]:.6e}")


OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4

Initial training data shape: X=(30, 4), y=(30,)
Initial best observation: -4.025542e+00


In [6]:
# Run Optuna-based BO for 8 weeks (8 iterations)
print("\nRunning Optuna-based BO for 8 iterations...")
print("-" * 60)

# Get all weekly data
weekly_data = [
    (week_1_inputs[3], week_1_outputs[3]),
    (week_2_inputs[3], week_2_outputs[3]),
    (week_3_inputs[3], week_3_outputs[3]),
    (week_4_inputs[3], week_4_outputs[3]),
    (week_5_inputs[3], week_5_outputs[3]),
    (week_6_inputs[3], week_6_outputs[3]),
    (week_7_inputs[3], week_7_outputs[3]),
    (week_8_inputs[3], week_8_outputs[3]),
    (week_9_inputs[3], week_9_outputs[3]),
    (week_10_inputs[3], week_10_outputs[3]),
    (week_11_inputs[3], week_11_outputs[3]),
    (week_12_inputs[3], week_12_outputs[3])
]

optuna_proposals_func4 = []
manual_best_func4 = week_0_func4_outputs.max()
optuna_best_func4 = y_func4_initial.max()

for week, (x_actual, y_actual) in enumerate(weekly_data, start=1):
    print(f"\nWeek {week}:")
    print(f"  Actual observation: y = {y_actual:.6e}")
    
    # Get Optuna proposal
    proposals = optimizer_func4.optimize(
        n_iterations=1,
        optimize_hp_every=1 if week % 2 == 0 else 0,  # Tune HP every other week
        optimize_hp_n_trials=30,
        acq_n_trials=100,
        verbose=True
    )
    
    x_proposed = proposals[0]
    optuna_proposals_func4.append(x_proposed)
    
    # Update optimizer with actual observation
    optimizer_func4.update(x_actual, y_actual)
    
    # Track best values
    manual_best_func4 = max(manual_best_func4, y_actual)
    optuna_best_func4 = max(optuna_best_func4, y_actual)
    
    print(f"  Best so far (Optuna): {optuna_best_func4:.6e}")

print("\n" + "=" * 60)
print("OPTUNA-BASED BO COMPLETED FOR FUNCTION 4")
print("=" * 60)



Running Optuna-based BO for 8 iterations...
------------------------------------------------------------

Week 1:
  Actual observation: y = -2.438723e+01


[I 2026-05-04 06:15:33,088] A new study created in memory with name: no-name-15469c74-5280-4569-94a1-4fdd3fdccef4
[I 2026-05-04 06:15:33,090] Trial 0 finished with value: -1.7118396596069267 and parameters: {'x0': 0.3745401188473625, 'x1': 0.9507143064099162, 'x2': 0.7319939418114051, 'x3': 0.5986584841970366}. Best is trial 0 with value: -1.7118396596069267.
[I 2026-05-04 06:15:33,092] Trial 1 finished with value: 2.4546816767793906 and parameters: {'x0': 0.15601864044243652, 'x1': 0.15599452033620265, 'x2': 0.05808361216819946, 'x3': 0.8661761457749352}. Best is trial 1 with value: 2.4546816767793906.
[I 2026-05-04 06:15:33,094] Trial 2 finished with value: 18.14495199475472 and parameters: {'x0': 0.6011150117432088, 'x1': 0.7080725777960455, 'x2': 0.020584494295802447, 'x3': 0.9699098521619943}. Best is trial 2 with value: 18.14495199475472.
[I 2026-05-04 06:15:33,096] Trial 3 finished with value: 10.301767262907081 and parameters: {'x0': 0.8324426408004217, 'x1': 0.2123391106782761

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 70.057964
  Best so far (Optuna): -4.025542e+00

Week 2:
  Actual observation: y = -1.336858e+01


[I 2026-05-04 06:15:34,240] Trial 20 finished with value: -5.71647832332043 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 14 with value: 49.52215188807962.
[I 2026-05-04 06:15:34,251] Trial 21 finished with value: 44.66897541138796 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 14 with value: 49.52215188807962.
[I 2026-05-04 06:15:34,259] Trial 22 finished with value: 39.610532870076824 and parameters: {'x0': 0.010989189243771236, 'x1': 0.6223665061627086, 'x2': 0.8984092422115008, 'x3': 0.7526280282294411}. Best is trial 14 with value: 49.52215188807962.
[I 2026-05-04 06:15:34,269] Trial 23 finished with value: 7.0658168395149215 and parameters: {'x0': 0.12604648636477472, 'x1': 0.4343150216117661, 'x2': 0.7789146329028911, 'x3': 0.020913566483403923}. Best is trial 14 with value: 49.52215188807962.
[I 2026-0

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 65.876200
  Best so far (Optuna): -4.025542e+00

Week 3:
  Actual observation: y = -2.111299e+01


[I 2026-05-04 06:15:35,237] Trial 19 finished with value: -8.454625050439912 and parameters: {'x0': 0.7298348295317013, 'x1': 0.30344630088855795, 'x2': 0.9093757578565972, 'x3': 0.8796139267265124}. Best is trial 14 with value: 49.52362459495343.
[I 2026-05-04 06:15:35,245] Trial 20 finished with value: -5.795712110774923 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 14 with value: 49.52362459495343.
[I 2026-05-04 06:15:35,254] Trial 21 finished with value: 43.64423590367156 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 14 with value: 49.52362459495343.
[I 2026-05-04 06:15:35,261] Trial 22 finished with value: 39.7735076014094 and parameters: {'x0': 0.010989189243771236, 'x1': 0.6223665061627086, 'x2': 0.8984092422115008, 'x3': 0.7526280282294411}. Best is trial 14 with value: 49.52362459495343.
[I 2026-05-0

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 65.529374
  Best so far (Optuna): -4.025542e+00

Week 4:
  Actual observation: y = 4.964978e-01


[I 2026-05-04 06:15:36,194] Trial 15 finished with value: -14.993880955235479 and parameters: {'x0': 0.9119167232179375, 'x1': 0.6895366011206421, 'x2': 0.8315564793402034, 'x3': 0.9495154109000117}. Best is trial 14 with value: 45.66372268109565.
[I 2026-05-04 06:15:36,201] Trial 16 finished with value: 9.8001568606985 and parameters: {'x0': 0.1830610799292295, 'x1': 0.29974150227632423, 'x2': 0.5170013476516693, 'x3': 0.8250042127507761}. Best is trial 14 with value: 45.66372268109565.
[I 2026-05-04 06:15:36,209] Trial 17 finished with value: 24.27503152167713 and parameters: {'x0': 0.24387496086356836, 'x1': 0.5586366447622301, 'x2': 0.8188959746902139, 'x3': 0.9828962113558958}. Best is trial 14 with value: 45.66372268109565.
[I 2026-05-04 06:15:36,216] Trial 18 finished with value: 15.474859863173151 and parameters: {'x0': 0.09039590229092491, 'x1': 0.5864590448357906, 'x2': 0.7365081229524856, 'x3': 0.5497458164140439}. Best is trial 14 with value: 45.66372268109565.
[I 2026-05-0

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 63.110453
  Best so far (Optuna): 4.964978e-01

Week 5:
  Actual observation: y = -1.716147e+01


[I 2026-05-04 06:15:37,277] Trial 19 finished with value: -1.307926022998597 and parameters: {'x0': 0.7298348295317013, 'x1': 0.30344630088855795, 'x2': 0.9093757578565972, 'x3': 0.8796139267265124}. Best is trial 11 with value: 68.54123865335788.
[I 2026-05-04 06:15:37,284] Trial 20 finished with value: -2.8224696273767655 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 11 with value: 68.54123865335788.
[I 2026-05-04 06:15:37,291] Trial 21 finished with value: 64.1111593571054 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 11 with value: 68.54123865335788.
[I 2026-05-04 06:15:37,298] Trial 22 finished with value: 55.82769930551595 and parameters: {'x0': 0.010989189243771236, 'x1': 0.6223665061627086, 'x2': 0.8984092422115008, 'x3': 0.7526280282294411}. Best is trial 11 with value: 68.54123865335788.
[I 2026-05-

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 89.123893
  Best so far (Optuna): 4.964978e-01

Week 6:
  Actual observation: y = 1.807654e-01


[I 2026-05-04 06:15:38,259] Trial 20 finished with value: -3.0912065761535032 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 11 with value: 66.48551621177845.
[I 2026-05-04 06:15:38,267] Trial 21 finished with value: 61.73259012285666 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 11 with value: 66.48551621177845.
[I 2026-05-04 06:15:38,274] Trial 22 finished with value: 52.61598088316139 and parameters: {'x0': 0.010989189243771236, 'x1': 0.6223665061627086, 'x2': 0.8984092422115008, 'x3': 0.7526280282294411}. Best is trial 11 with value: 66.48551621177845.
[I 2026-05-04 06:15:38,284] Trial 23 finished with value: 10.324518206240352 and parameters: {'x0': 0.12604648636477472, 'x1': 0.4343150216117661, 'x2': 0.7789146329028911, 'x3': 0.020913566483403923}. Best is trial 11 with value: 66.48551621177845.
[I 2026-

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 87.445130
  Best so far (Optuna): 4.964978e-01

Week 7:
  Actual observation: y = -1.158523e+01


[I 2026-05-04 06:15:39,220] Trial 15 finished with value: -9.342351755274741 and parameters: {'x0': 0.9119167232179375, 'x1': 0.6895366011206421, 'x2': 0.8315564793402034, 'x3': 0.9495154109000117}. Best is trial 11 with value: 64.97926146929072.
[I 2026-05-04 06:15:39,227] Trial 16 finished with value: 13.496064369770952 and parameters: {'x0': 0.1830610799292295, 'x1': 0.29974150227632423, 'x2': 0.5170013476516693, 'x3': 0.8250042127507761}. Best is trial 11 with value: 64.97926146929072.
[I 2026-05-04 06:15:39,234] Trial 17 finished with value: 37.864925386585924 and parameters: {'x0': 0.24387496086356836, 'x1': 0.5586366447622301, 'x2': 0.8188959746902139, 'x3': 0.9828962113558958}. Best is trial 11 with value: 64.97926146929072.
[I 2026-05-04 06:15:39,241] Trial 18 finished with value: 21.146978817085603 and parameters: {'x0': 0.09039590229092491, 'x1': 0.5864590448357906, 'x2': 0.7365081229524856, 'x3': 0.5497458164140439}. Best is trial 11 with value: 64.97926146929072.
[I 2026-0

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 87.917840
  Best so far (Optuna): 4.964978e-01

Week 8:
  Actual observation: y = -3.366179e+01


[I 2026-05-04 06:15:40,199] Trial 14 finished with value: 73.42043240420134 and parameters: {'x0': 0.010813209728300745, 'x1': 0.5760103475555451, 'x2': 0.8325281155031543, 'x3': 0.9371047292979525}. Best is trial 11 with value: 76.12389195454156.
[I 2026-05-04 06:15:40,207] Trial 15 finished with value: -6.320917932846164 and parameters: {'x0': 0.9119167232179375, 'x1': 0.6895366011206421, 'x2': 0.8315564793402034, 'x3': 0.9495154109000117}. Best is trial 11 with value: 76.12389195454156.
[I 2026-05-04 06:15:40,215] Trial 16 finished with value: 15.687942499883576 and parameters: {'x0': 0.1830610799292295, 'x1': 0.29974150227632423, 'x2': 0.5170013476516693, 'x3': 0.8250042127507761}. Best is trial 11 with value: 76.12389195454156.
[I 2026-05-04 06:15:40,222] Trial 17 finished with value: 46.02171614630966 and parameters: {'x0': 0.24387496086356836, 'x1': 0.5586366447622301, 'x2': 0.8188959746902139, 'x3': 0.9828962113558958}. Best is trial 11 with value: 76.12389195454156.
[I 2026-05

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], UCB: 100.026574
  Best so far (Optuna): 4.964978e-01

Week 9:
  Actual observation: y = -3.366179e+01


[I 2026-05-04 06:15:41,231] Trial 16 finished with value: 17.76399840457796 and parameters: {'x0': 0.10870898127002515, 'x1': 0.5849021569336816, 'x2': 0.855621758265883, 'x3': 0.9960165317474353}. Best is trial 8 with value: 48.056730183812206.
[I 2026-05-04 06:15:41,239] Trial 17 finished with value: 14.622044728087708 and parameters: {'x0': 0.254949019199943, 'x1': 0.8227792903496551, 'x2': 0.9993624386415512, 'x3': 0.8109884180296526}. Best is trial 8 with value: 48.056730183812206.
[I 2026-05-04 06:15:41,249] Trial 18 finished with value: 18.581339454762556 and parameters: {'x0': 0.025549494810543194, 'x1': 0.3305796679853261, 'x2': 0.7890446554500232, 'x3': 0.6446736852680854}. Best is trial 8 with value: 48.056730183812206.
[I 2026-05-04 06:15:41,259] Trial 19 finished with value: -12.091791846470143 and parameters: {'x0': 0.7298348295317013, 'x1': 0.8655059117256985, 'x2': 0.43676329853917906, 'x3': 0.8796139267265124}. Best is trial 8 with value: 48.056730183812206.
[I 2026-05

[Iteration 0] Proposed: [0.00109021 0.90206867 0.97221209 0.16754021], UCB: 78.588840
  Best so far (Optuna): 4.964978e-01

Week 10:
  Actual observation: y = -3.013309e+01


[I 2026-05-04 06:15:42,217] Trial 15 finished with value: -3.0224013778424847 and parameters: {'x0': 0.9119167232179375, 'x1': 0.32176717760026485, 'x2': 0.5230267959649637, 'x3': 0.5716692432284404}. Best is trial 8 with value: 48.05649503518126.
[I 2026-05-04 06:15:42,225] Trial 16 finished with value: 17.763839554888833 and parameters: {'x0': 0.10870898127002515, 'x1': 0.5849021569336816, 'x2': 0.855621758265883, 'x3': 0.9960165317474353}. Best is trial 8 with value: 48.05649503518126.
[I 2026-05-04 06:15:42,233] Trial 17 finished with value: 14.621867210835315 and parameters: {'x0': 0.254949019199943, 'x1': 0.8227792903496551, 'x2': 0.9993624386415512, 'x3': 0.8109884180296526}. Best is trial 8 with value: 48.05649503518126.
[I 2026-05-04 06:15:42,239] Trial 18 finished with value: 18.581207946626122 and parameters: {'x0': 0.025549494810543194, 'x1': 0.3305796679853261, 'x2': 0.7890446554500232, 'x3': 0.6446736852680854}. Best is trial 8 with value: 48.05649503518126.
[I 2026-05-04

[Iteration 0] Proposed: [0.00109021 0.90206867 0.97221209 0.16754021], UCB: 78.588601
  Best so far (Optuna): 4.964978e-01

Week 11:
  Actual observation: y = -3.174484e+01


[I 2026-05-04 06:15:43,193] Trial 13 finished with value: 21.88701462316002 and parameters: {'x0': 0.1834425227544209, 'x1': 0.9919433969899397, 'x2': 0.8606835739054293, 'x3': 0.6766877950436359}. Best is trial 8 with value: 49.67187632031144.
[I 2026-05-04 06:15:43,201] Trial 14 finished with value: 11.278241048862647 and parameters: {'x0': 0.16005384799155248, 'x1': 0.652026524508901, 'x2': 0.8327447046767401, 'x3': 0.8553961953522018}. Best is trial 8 with value: 49.67187632031144.
[I 2026-05-04 06:15:43,208] Trial 15 finished with value: -1.778194615973991 and parameters: {'x0': 0.9119167232179375, 'x1': 0.32176717760026485, 'x2': 0.5230267959649637, 'x3': 0.5716692432284404}. Best is trial 8 with value: 49.67187632031144.
[I 2026-05-04 06:15:43,216] Trial 16 finished with value: 22.375643484522172 and parameters: {'x0': 0.10870898127002515, 'x1': 0.5849021569336816, 'x2': 0.855621758265883, 'x3': 0.9960165317474353}. Best is trial 8 with value: 49.67187632031144.
[I 2026-05-04 06

[Iteration 0] Proposed: [0.01881756 0.99890415 0.99965779 0.99801573], UCB: 89.921882
  Best so far (Optuna): 4.964978e-01

Week 12:
  Actual observation: y = -4.762748e+01


[I 2026-05-04 06:15:44,184] Trial 18 finished with value: 2.8226623615733573 and parameters: {'x0': 0.2679894238413223, 'x1': 0.8399735993147213, 'x2': 0.7641433740296321, 'x3': 0.8792478878697052}. Best is trial 8 with value: 42.969743791284266.
[I 2026-05-04 06:15:44,192] Trial 19 finished with value: -2.519144857075011 and parameters: {'x0': 0.49048816631267056, 'x1': 0.8612450581269565, 'x2': 0.43890252579858813, 'x3': 0.7795607538464874}. Best is trial 8 with value: 42.969743791284266.
[I 2026-05-04 06:15:44,199] Trial 20 finished with value: 12.77398897616542 and parameters: {'x0': 0.22738385686221219, 'x1': 0.9089669756133171, 'x2': 0.6334928879354629, 'x3': 0.9317507286943678}. Best is trial 8 with value: 42.969743791284266.
[I 2026-05-04 06:15:44,206] Trial 21 finished with value: 25.864394449438933 and parameters: {'x0': 0.09313558989669676, 'x1': 0.6590286048089739, 'x2': 0.8748194629192568, 'x3': 0.9692698520487176}. Best is trial 8 with value: 42.969743791284266.
[I 2026-0

[Iteration 0] Proposed: [0.05223903 0.97259986 0.99820983 0.97670822], UCB: 74.421718
  Best so far (Optuna): 4.964978e-01

OPTUNA-BASED BO COMPLETED FOR FUNCTION 4
