In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from scipy.stats import norm
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

/Users/martindufour/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Function 4
print('Function 4')
func4_inputs = np.load('./initial_data/function_4/initial_inputs.npy')
print(func4_inputs)

func4_outputs = np.load('./initial_data/function_4/initial_outputs.npy')
print(func4_outputs)
print('/n')

Function 4
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [

In [3]:
# Week 1 Input and Output Data
week_1_inputs = [ np.array([0.155793, 0.528435]), np.array([0.224164, 0.812385]), np.array([0.830919, 0.158523, 0.528406]), np.array([0.912533, 0.052672, 0.771239, 0.219812]), np.array([0.234189, 0.83648 , 0.884484, 0.873516]), np.array([0.490808, 0.618683, 0.277824, 0.900494, 0.106596]), np.array([0.067896, 0.486672, 0.255422, 0.215118, 0.427428, 0.72097 ]), np.array([0.061447, 0.062956, 0.029929, 0.036786, 0.407935, 0.795055, 0.496307,0.888085]) ]
week_1_outputs = [np.float64(1.5311489892413605e-58), np.float64(0.04614596805685454), np.float64(-0.04591165123945737), np.float64(-24.387232512869755), np.float64(1049.4420694211206), np.float64(-0.849252655626155), np.float64(1.3793294734939503), np.float64(9.598780741169)]

week_2_inputs = [np.array([0.946399, 0.18731 ]), np.array([0.712637, 0.921564]), np.array([0.765104, 0.052672, 0.438597]), np.array([0.380965, 0.771701, 0.089479, 0.536968]), np.array([0.219189, 0.85148 , 0.874484, 0.883516]), np.array([0.114755, 0.697421, 0.354179, 0.887624, 0.589139]), np.array([0.070896, 0.484672, 0.259422, 0.216118, 0.427428, 0.72297 ]), np.array([0.062447, 0.061956, 0.030929, 0.035786, 0.408935, 0.794055, 0.497307, 0.887085])]
week_2_outputs = [np.float64(2.338449488843798e-206), np.float64(0.5728372778652475), np.float64(-0.10235480701941752), np.float64(-13.368584815829887), np.float64(1109.9883069580462), np.float64(-1.492909868264592), np.float64(1.3944037721068683), np.float64(9.598978827169)]

week_3_inputs = [np.array([0.583738, 0.706798]), np.array([0.699637, 0.928564]), np.array([0.123457, 0.876543, 0.5     ]), np.array([0.230785, 0.914568, 0.102938, 0.657322]), np.array([0.214189, 0.85648 , 0.869484, 0.888516]), np.array([0.051235, 0.987654, 0.43211 , 0.123457, 0.765432]), np.array([0.071896, 0.483672, 0.261422, 0.217118, 0.426428, 0.72497 ]), np.array([0.063447, 0.060956, 0.031929, 0.034786, 0.409935, 0.793055, 0.498307, 0.886085])]
week_3_outputs = [np.float64(9.817718646044271e-07), np.float64(0.49978778689465564), np.float64(-0.04054152149606349), np.float64(-21.112987453792396), np.float64(1132.5255136709882), np.float64(-2.4679805862566795), np.float64(1.4059619293543582), np.float64(9.599155713169)]

week_4_inputs = [np.array([0.867072, 0.913241]), np.array([0.83604 , 0.696071]), np.array([0.447658, 0.395195, 0.505344]), np.array([0.422706, 0.385497, 0.37529 , 0.410833]), np.array([0.157706, 0.912326, 0.830158, 0.925715]), np.array([0.275401, 0.      , 0.568079, 1.      , 0.121326]), np.array([0.124679, 0.389027, 0.389012, 0.23686 , 0.379036, 0.802247]), np.array([0.077447, 0.21029 , 0.114032, 0.159535, 0.695924, 0.531316,0.178973, 0.57168 ])]
week_4_outputs = [np.float64(-1.0508862613282513e-96), np.float64(0.20657541488475104), np.float64(-0.03229682155733878), np.float64(0.4964978124935766), np.float64(1445.380906735266), np.float64(-0.8152779914672599), np.float64(2.0217812896063525), np.float64(9.987130922543)]

week_5_inputs = [np.array([0.065052, 0.948886]), np.array([0.388677, 0.271349]), np.array([1.      , 0.136717, 0.850593]), np.array([0.908266, 0.239562, 0.144895, 0.489453]), np.array([0.115614, 0.955641, 0.820859, 0.938174]), np.array([0.568442, 0.      , 1.      , 1.      , 1.      ]), np.array([0.134015, 0.028783, 0.755137, 0.62031 , 0.70408 , 0.212964]), np.array([0.127008, 0.292876, 0.06967 , 0.277582, 0.553407, 0.547258,0.220835, 0.443146])]
week_5_outputs = [np.float64(2.0262778967114778e-283), np.float64(0.016418658339648333), np.float64(-0.054388754089278846), np.float64(-17.161465002411145), np.float64(1779.8600577462366), np.float64(-1.9906490554141107), np.float64(0.052467603616080494), np.float64(9.9149654065019)]

week_6_inputs = [np.array([0.17701 , 0.088703]), np.array([0.593592, 0.679102]), np.array([0.7536, 1.    , 1.    ]), np.array([0.370348, 0.379959, 0.430216, 0.444351]), np.array([0.169493, 0.556801, 0.936155, 0.69603 ]), np.array([0.366464, 0.316099, 1.      , 1.      , 0.      ]), np.array([0.123574, 0.270452, 0.482301, 0.208163, 0.330398, 0.872733]), np.array([0.3191  , 0.828915, 0.037008, 0.59627 , 0.230009, 0.120567,0.076953, 0.696289])]
week_6_outputs = [np.float64(-2.3725238219366144e-119), np.float64(0.06836721478932847), np.float64(-0.48310415434111403), np.float64(0.18076540708623456), np.float64(282.83820524691396), np.float64(-0.8214281898088153), np.float64(2.075605759888563), np.float64(8.8803427965834)]

week_7_inputs = [np.array([0.065052, 0.948886]), np.array([0.140924, 0.802197]), np.array([1., 1., 0.]), np.array([0.32078 , 0.186519, 0.040775, 0.590893]), np.array([0.548734, 0.691895, 0.651961, 0.224269]), np.array([0.368433, 0.      , 1.      , 1.      , 0.428022]), np.array([0.139689, 0.317433, 0.463608, 0.250431, 0.325485, 0.810756]), np.array([0.      , 0.202823, 0.231703, 0.      , 1.      , 1.      ,
       0.288474, 1.      ])]
week_7_outputs = [np.float64(2.0262778967114778e-283), np.float64(-0.10826299524356352), np.float64(-0.16354530625442043), np.float64(-11.58523458824008), np.float64(1.9931553503870212), np.float64(-1.2796687884296385), np.float64(2.462201676843452), np.float64(9.622023932692)]

week_8_inputs = [np.array([0.000788, 0.033717]), np.array([0.914607, 0.789979]), np.array([0.317253, 0.002183, 0.963506]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.078217, 0.973099, 0.868006, 0.933352]), np.array([0.426158, 0.348959, 0.616644, 0.692851, 0.024814]), np.array([0.269889, 0.346609, 0.467584, 0.256632, 0.302654, 0.800092]), np.array([0.066269, 0.029193, 0.143059, 0.209133, 0.840619, 0.604919,
       0.230297, 0.701468])]
week_8_outputs = [np.float64(1.5608341712501477e-228), np.float64(0.0347797753016137), np.float64(-0.3756702789549372), np.float64(-33.661790988299735), np.float64(2151.3700669834334), np.float64(-0.23000336822278494), np.float64(2.4516632535923746), np.float64(9.9644234438351)]

week_9_inputs = [np.array([0.000924, 0.003116]), np.array([0.914607, 0.789979]), np.array([0.047574, 0.998325, 0.999125]), np.array([0.008334, 0.234163, 0.946857, 0.993453]), np.array([0.080698, 0.971918, 0.842327, 0.954471]), np.array([0.942348, 0.037756, 0.105925, 0.010348, 0.997595]), np.array([0.090198, 0.680559, 0.851748, 0.080076, 0.298474, 0.701193]), np.array([0.95983 , 0.002073, 0.011779, 0.227207, 0.571611, 0.031204,
       0.24468 , 0.055697])]
week_9_outputs = [np.float64(7.25285761175276e-246), np.float64(0.05670257386671321), np.float64(-0.48158498276260003), np.float64(-33.661790988299735), np.float64(2156.522419821577), np.float64(-3.026993482898997), np.float64(0.6117443854593981), np.float64(8.1721431718416)]

In [4]:
# Function 4
print('Function 4')
# Load inputs from previous run
# Loads initial data
week_0_func4_inputs = np.load('./initial_data/function_4/initial_inputs.npy')
week_0_func4_outputs = np.load('./initial_data/function_4/initial_outputs.npy')

print(f'Shape of initial input data: {week_0_func4_inputs.shape}')
print(f'Shape of initial output data: {week_0_func4_outputs.shape}')

print(f'Week 1 inputs: {week_1_inputs[3]}')
print(f'Week 2 inputs: {week_2_inputs[3]}')
print(f'Week 3 inputs: {week_3_inputs[3]}')
print(f'Week 4 inputs: {week_4_inputs[3]}')
print(f'Week 5 inputs: {week_5_inputs[3]}')
print(f'Week 6 inputs: {week_6_inputs[3]}')
print(f'Week 7 inputs: {week_7_inputs[3]}')
print(f'Week 8 inputs: {week_8_inputs[3]}')
print(f'Week 9 inputs: {week_9_inputs[3]}')

combined_func4_inputs = np.vstack([
    week_0_func4_inputs,
    week_1_inputs[3],
    week_2_inputs[3],
    week_3_inputs[3],
    week_4_inputs[3],
    week_5_inputs[3],
    week_6_inputs[3],
    week_7_inputs[3],
    week_8_inputs[3],
    week_9_inputs[3]
])
print(f'Number of input data points: {len(combined_func4_inputs)}')
print('Combined input data')
print(combined_func4_inputs)

# Load outputs from previous run
week_func4_output = week_1_outputs[3]
combined_func4_outputs = np.concatenate([
    week_0_func4_outputs,
    [week_1_outputs[3]],
    [week_2_outputs[3]],
    [week_3_outputs[3]],
    [week_4_outputs[3]],
    [week_5_outputs[3]],
    [week_6_outputs[3]],
    [week_7_outputs[3]],
    [week_8_outputs[3]],
    [week_9_outputs[3]]
])
print(f'Number of output data points: {len(combined_func4_outputs)}')
print('Combined output data')
print(combined_func4_outputs)

Function 4
Shape of initial input data: (30, 4)
Shape of initial output data: (30,)
Week 1 inputs: [0.912533 0.052672 0.771239 0.219812]
Week 2 inputs: [0.380965 0.771701 0.089479 0.536968]
Week 3 inputs: [0.230785 0.914568 0.102938 0.657322]
Week 4 inputs: [0.422706 0.385497 0.37529  0.410833]
Week 5 inputs: [0.908266 0.239562 0.144895 0.489453]
Week 6 inputs: [0.370348 0.379959 0.430216 0.444351]
Week 7 inputs: [0.32078  0.186519 0.040775 0.590893]
Week 8 inputs: [0.008334 0.234163 0.946857 0.993453]
Week 9 inputs: [0.008334 0.234163 0.946857 0.993453]
Number of input data points: 39
Combined input data
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.4006650

In [5]:
### ====== OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4 ======
# Import the OptunaBayesianOptimizer class
import sys
sys.path.insert(0, './bayesian_optimization_challenge-md')
from bo_optuna import OptunaBayesianOptimizer

# Create optimizer instance with initial Function 4 data
print("=" * 60)
print("OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4")
print("=" * 60)

X_func4_initial = week_0_func4_inputs
y_func4_initial = week_0_func4_outputs
bounds_func4 = [(0, 1)] * X_func4_initial.shape[1]

optimizer_func4 = OptunaBayesianOptimizer(
    X_initial=X_func4_initial,
    y_initial=y_func4_initial,
    bounds=bounds_func4,
    optimize_hp=True,  # Enable hyperparameter tuning
    random_state=42,
    acquisition="ei"
)

print(f"\nInitial training data shape: X={optimizer_func4.X_train.shape}, y={optimizer_func4.y_train.shape}")
print(f"Initial best observation: {optimizer_func4.get_best_observation()[1]:.6e}")


OPTUNA-BASED BAYESIAN OPTIMIZATION FOR FUNCTION 4

Initial training data shape: X=(30, 4), y=(30,)
Initial best observation: -4.025542e+00


In [6]:
# Run Optuna-based BO for 8 weeks (8 iterations)
print("\nRunning Optuna-based BO for 8 iterations...")
print("-" * 60)

# Get all weekly data
weekly_data = [
    (week_1_inputs[3], week_1_outputs[3]),
    (week_2_inputs[3], week_2_outputs[3]),
    (week_3_inputs[3], week_3_outputs[3]),
    (week_4_inputs[3], week_4_outputs[3]),
    (week_5_inputs[3], week_5_outputs[3]),
    (week_6_inputs[3], week_6_outputs[3]),
    (week_7_inputs[3], week_7_outputs[3]),
    (week_8_inputs[3], week_8_outputs[3]),
    (week_9_inputs[3], week_9_outputs[3])
]

optuna_proposals_func4 = []
manual_best_func4 = week_0_func4_outputs.max()
optuna_best_func4 = y_func4_initial.max()

for week, (x_actual, y_actual) in enumerate(weekly_data, start=1):
    print(f"\nWeek {week}:")
    print(f"  Actual observation: y = {y_actual:.6e}")
    
    # Get Optuna proposal
    proposals = optimizer_func4.optimize(
        n_iterations=1,
        optimize_hp_every=1 if week % 2 == 0 else 0,  # Tune HP every other week
        optimize_hp_n_trials=30,
        acq_n_trials=100,
        verbose=True
    )
    
    x_proposed = proposals[0]
    optuna_proposals_func4.append(x_proposed)
    
    # Update optimizer with actual observation
    optimizer_func4.update(x_actual, y_actual)
    
    # Track best values
    manual_best_func4 = max(manual_best_func4, y_actual)
    optuna_best_func4 = max(optuna_best_func4, y_actual)
    
    print(f"  Best so far (Optuna): {optuna_best_func4:.6e}")

print("\n" + "=" * 60)
print("OPTUNA-BASED BO COMPLETED FOR FUNCTION 4")
print("=" * 60)



Running Optuna-based BO for 8 iterations...
------------------------------------------------------------

Week 1:
  Actual observation: y = -2.438723e+01


[I 2026-04-20 19:34:58,515] A new study created in memory with name: no-name-b7b99e3c-61d2-4438-bb3a-5bef23286573
[I 2026-04-20 19:34:58,517] Trial 0 finished with value: 1.6315704878666344e-41 and parameters: {'x0': 0.3745401188473625, 'x1': 0.9507143064099162, 'x2': 0.7319939418114051, 'x3': 0.5986584841970366}. Best is trial 0 with value: 1.6315704878666344e-41.
[I 2026-04-20 19:34:58,519] Trial 1 finished with value: 6.047868141745643e-28 and parameters: {'x0': 0.15601864044243652, 'x1': 0.15599452033620265, 'x2': 0.05808361216819946, 'x3': 0.8661761457749352}. Best is trial 1 with value: 6.047868141745643e-28.
[I 2026-04-20 19:34:58,523] Trial 2 finished with value: 1.3914196986116335e-14 and parameters: {'x0': 0.6011150117432088, 'x1': 0.7080725777960455, 'x2': 0.020584494295802447, 'x3': 0.9699098521619943}. Best is trial 2 with value: 1.3914196986116335e-14.
[I 2026-04-20 19:34:58,525] Trial 3 finished with value: 6.273938921685125e-12 and parameters: {'x0': 0.8324426408004217,

[Iteration 0] Proposed: [0.41363589 0.40151382 0.34054867 0.35342027], EI: 2.708660
  Best so far (Optuna): -4.025542e+00

Week 2:
  Actual observation: y = -1.336858e+01


[I 2026-04-20 19:34:59,744] Trial 17 finished with value: 1.4856405888546597e-06 and parameters: {'x0': 0.16191235238118648, 'x1': 0.5257122542929031, 'x2': 0.37953307704655603, 'x3': 0.2715395652676304}. Best is trial 4 with value: 0.37661871630256516.
[I 2026-04-20 19:34:59,753] Trial 18 finished with value: 0.1927442634587424 and parameters: {'x0': 0.29611177716868736, 'x1': 0.30068318549670203, 'x2': 0.17511150192118183, 'x3': 0.46140483948688765}. Best is trial 4 with value: 0.37661871630256516.
[I 2026-04-20 19:34:59,765] Trial 19 finished with value: 6.432604390517504e-05 and parameters: {'x0': 0.5157315366378478, 'x1': 0.30344630088855795, 'x2': 0.13881283755258783, 'x3': 0.6532578158651132}. Best is trial 4 with value: 0.37661871630256516.
[I 2026-04-20 19:34:59,776] Trial 20 finished with value: 0.01570263224476176 and parameters: {'x0': 0.34823993441709794, 'x1': 0.26236543566349396, 'x2': 0.109778852397933, 'x3': 0.4864346467540252}. Best is trial 4 with value: 0.3766187163

[Iteration 0] Proposed: [0.41363589 0.40151382 0.34054867 0.35342027], EI: 2.713138
  Best so far (Optuna): -4.025542e+00

Week 3:
  Actual observation: y = -2.111299e+01


[I 2026-04-20 19:35:00,852] Trial 15 finished with value: 2.4564497896886737e-31 and parameters: {'x0': 0.45098458139064684, 'x1': 0.32176717760026485, 'x2': 0.46870521888784217, 'x3': 0.07054830010046476}. Best is trial 4 with value: 0.4307505067319401.
[I 2026-04-20 19:35:00,862] Trial 16 finished with value: 3.3585875879290837e-09 and parameters: {'x0': 0.20027745328836177, 'x1': 0.5046009694696039, 'x2': 0.7926421099078276, 'x3': 0.46411592902568616}. Best is trial 4 with value: 0.4307505067319401.
[I 2026-04-20 19:35:00,871] Trial 17 finished with value: 0.03052390805442247 and parameters: {'x0': 0.3791383463468019, 'x1': 0.2667781496521552, 'x2': 0.37953307704655603, 'x3': 0.20924824502462858}. Best is trial 4 with value: 0.4307505067319401.
[I 2026-04-20 19:35:00,880] Trial 18 finished with value: 1.2805099697959823e-09 and parameters: {'x0': 0.025549494810543194, 'x1': 0.2844583074120003, 'x2': 0.8711464908919611, 'x3': 0.18226632108300603}. Best is trial 4 with value: 0.430750

[Iteration 0] Proposed: [0.39233641 0.40724227 0.31739116 0.3922235 ], EI: 2.645785
  Best so far (Optuna): -4.025542e+00

Week 4:
  Actual observation: y = 4.964978e-01


[I 2026-04-20 19:35:01,930] Trial 18 finished with value: 4.830624540324651e-10 and parameters: {'x0': 0.025549494810543194, 'x1': 0.2844583074120003, 'x2': 0.8711464908919611, 'x3': 0.18226632108300603}. Best is trial 4 with value: 0.40493164736198733.
[I 2026-04-20 19:35:01,938] Trial 19 finished with value: 1.1537364239785298e-60 and parameters: {'x0': 0.37081316879646914, 'x1': 0.4743170417801599, 'x2': 0.5844813233874214, 'x3': 0.09239286120181393}. Best is trial 4 with value: 0.40493164736198733.
[I 2026-04-20 19:35:01,946] Trial 20 finished with value: 6.362632004843971e-53 and parameters: {'x0': 0.11677223676079723, 'x1': 0.7516134248157891, 'x2': 0.3757425324647367, 'x3': 0.22750997267773515}. Best is trial 4 with value: 0.40493164736198733.
[I 2026-04-20 19:35:01,953] Trial 21 finished with value: 8.89120818824455e-06 and parameters: {'x0': 0.3620029301153167, 'x1': 0.17912696721097643, 'x2': 0.1480970895412116, 'x3': 0.40144338366858645}. Best is trial 4 with value: 0.404931

[Iteration 0] Proposed: [0.39233641 0.40724227 0.31739116 0.3922235 ], EI: 2.631813
  Best so far (Optuna): 4.964978e-01

Week 5:
  Actual observation: y = -1.716147e+01


[I 2026-04-20 19:35:02,965] Trial 18 finished with value: 9.828373257880751e-08 and parameters: {'x0': 0.09039590229092491, 'x1': 0.5864590448357906, 'x2': 0.7365081229524856, 'x3': 0.5497458164140439}. Best is trial 14 with value: 7.15823215304166e-05.
[I 2026-04-20 19:35:02,973] Trial 19 finished with value: 1.059037013952421e-59 and parameters: {'x0': 0.7298348295317013, 'x1': 0.30344630088855795, 'x2': 0.9093757578565972, 'x3': 0.8796139267265124}. Best is trial 14 with value: 7.15823215304166e-05.
[I 2026-04-20 19:35:02,981] Trial 20 finished with value: 1.305567140819895e-85 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 14 with value: 7.15823215304166e-05.
[I 2026-04-20 19:35:02,987] Trial 21 finished with value: 2.673772414109256e-05 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 14 with value: 7.158232

[Iteration 0] Proposed: [4.74455104e-04 3.12834141e-01 9.01181140e-01 9.98961091e-01], EI: 0.000538
  Best so far (Optuna): 4.964978e-01

Week 6:
  Actual observation: y = 1.807654e-01


[I 2026-04-20 19:35:03,995] Trial 18 finished with value: 3.3072411550775897e-08 and parameters: {'x0': 0.09039590229092491, 'x1': 0.5864590448357906, 'x2': 0.7365081229524856, 'x3': 0.5497458164140439}. Best is trial 14 with value: 5.95743166584453e-05.
[I 2026-04-20 19:35:04,002] Trial 19 finished with value: 1.3476586694216035e-61 and parameters: {'x0': 0.7298348295317013, 'x1': 0.30344630088855795, 'x2': 0.9093757578565972, 'x3': 0.8796139267265124}. Best is trial 14 with value: 5.95743166584453e-05.
[I 2026-04-20 19:35:04,012] Trial 20 finished with value: 1.5280694926494007e-89 and parameters: {'x0': 0.4134140996927128, 'x1': 0.8152590804011591, 'x2': 0.5587985830433142, 'x3': 0.629540378885119}. Best is trial 14 with value: 5.95743166584453e-05.
[I 2026-04-20 19:35:04,018] Trial 21 finished with value: 1.9229421968999078e-05 and parameters: {'x0': 0.03720314284198487, 'x1': 0.4456913325009603, 'x2': 0.9987035778664451, 'x3': 0.7482952279132283}. Best is trial 14 with value: 5.95

[Iteration 0] Proposed: [0.00301571 0.32577568 0.89822828 0.99423852], EI: 0.000401
  Best so far (Optuna): 4.964978e-01

Week 7:
  Actual observation: y = -1.158523e+01


[I 2026-04-20 19:35:05,099] Trial 16 finished with value: 2.0273222020851183e-15 and parameters: {'x0': 0.1830610799292295, 'x1': 0.29974150227632423, 'x2': 0.5170013476516693, 'x3': 0.8250042127507761}. Best is trial 11 with value: 1.662468721796127e-05.
[I 2026-04-20 19:35:05,108] Trial 17 finished with value: 3.0214856940416546e-09 and parameters: {'x0': 0.24387496086356836, 'x1': 0.5586366447622301, 'x2': 0.8188959746902139, 'x3': 0.9828962113558958}. Best is trial 11 with value: 1.662468721796127e-05.
[I 2026-04-20 19:35:05,115] Trial 18 finished with value: 2.460148083001792e-10 and parameters: {'x0': 0.09039590229092491, 'x1': 0.5864590448357906, 'x2': 0.7365081229524856, 'x3': 0.5497458164140439}. Best is trial 11 with value: 1.662468721796127e-05.
[I 2026-04-20 19:35:05,124] Trial 19 finished with value: 2.8167996520362145e-58 and parameters: {'x0': 0.7298348295317013, 'x1': 0.30344630088855795, 'x2': 0.9093757578565972, 'x3': 0.8796139267265124}. Best is trial 11 with value: 

[Iteration 0] Proposed: [0.04441635 0.40638662 0.99969574 0.98121896], EI: 0.000244
  Best so far (Optuna): 4.964978e-01

Week 8:
  Actual observation: y = -3.366179e+01


[I 2026-04-20 19:35:06,156] Trial 11 finished with value: 0.00044982906818032825 and parameters: {'x0': 0.014540875162364394, 'x1': 0.40166479415670114, 'x2': 0.9871021105281521, 'x3': 0.7610683248568721}. Best is trial 11 with value: 0.00044982906818032825.
[I 2026-04-20 19:35:06,164] Trial 12 finished with value: 0.00011151672046715369 and parameters: {'x0': 0.03435746358874557, 'x1': 0.3796042434202234, 'x2': 0.9958455863174286, 'x3': 0.6794924716198952}. Best is trial 11 with value: 0.00044982906818032825.
[I 2026-04-20 19:35:06,171] Trial 13 finished with value: 1.2090515603791155e-07 and parameters: {'x0': 0.1755099159333286, 'x1': 0.415080301587867, 'x2': 0.8578630514651198, 'x3': 0.7255603602505948}. Best is trial 11 with value: 0.00044982906818032825.
[I 2026-04-20 19:35:06,180] Trial 14 finished with value: 0.0005317053163777143 and parameters: {'x0': 0.010813209728300745, 'x1': 0.5760103475555451, 'x2': 0.8325281155031543, 'x3': 0.9371047292979525}. Best is trial 14 with val

[Iteration 0] Proposed: [0.00833442 0.23416318 0.94685671 0.99345325], EI: 0.006409
  Best so far (Optuna): 4.964978e-01

Week 9:
  Actual observation: y = -3.366179e+01


[I 2026-04-20 19:35:07,350] Trial 13 finished with value: 2.1542487744432552e-16 and parameters: {'x0': 0.1834425227544209, 'x1': 0.9919433969899397, 'x2': 0.8606835739054293, 'x3': 0.6766877950436359}. Best is trial 8 with value: 1.3217114788792783e-08.
[I 2026-04-20 19:35:07,359] Trial 14 finished with value: 4.812357241797461e-29 and parameters: {'x0': 0.16005384799155248, 'x1': 0.652026524508901, 'x2': 0.8327447046767401, 'x3': 0.8553961953522018}. Best is trial 8 with value: 1.3217114788792783e-08.
[I 2026-04-20 19:35:07,367] Trial 15 finished with value: 7.320820223046992e-84 and parameters: {'x0': 0.9119167232179375, 'x1': 0.32176717760026485, 'x2': 0.5230267959649637, 'x3': 0.5716692432284404}. Best is trial 8 with value: 1.3217114788792783e-08.
[I 2026-04-20 19:35:07,379] Trial 16 finished with value: 7.741664588759978e-22 and parameters: {'x0': 0.10870898127002515, 'x1': 0.5849021569336816, 'x2': 0.855621758265883, 'x3': 0.9960165317474353}. Best is trial 8 with value: 1.3217

[Iteration 0] Proposed: [0.0277463  0.65493663 0.99965203 0.02467392], EI: 0.001317
  Best so far (Optuna): 4.964978e-01

OPTUNA-BASED BO COMPLETED FOR FUNCTION 4
